### ISSUE TITLE
Batch sending using provider variables, maintainable mail templates

### ISSUE THREAD

**Issue by stefanosc** [jpmckinney/multi_mail#23]
First of all thank you for this gem, it looks great.
I am considering implementing a mailer for a project to send emails in batch. Providers allow you to do so that you make less api calls, and sending is more efficient.

To do so you have to use provider specific templating (madrill merge_vars / mailgun variables etc..).  
I thought it would be nice to have templates simply the rails way so they are provider independent, and then pre-process the template before sending for the specific provider.  

This would make the code more maintainable.  
I was wondering if you have ever considered this aspect (although slightly out of scope for this gem..)  

Thank you!

**Comment by jpmckinney** [comment]
I haven't considered it, but I would merge a pull request that added this feature!

**Comment by stefanosc** [comment]
Thank you for the quick response!

Ok I think I could work on a PR.
I'm thinking could be some sort of mail rendering for specific providers.

I'll have to play around with some templates and provider docs to
understand what is required, initially I thought it could be simple but
there is some complexity involved, it's a mini template engine basically.

Do you have any suggestion on terms of implementation requirements or
ideas?

Thanks again!

**Comment by jpmckinney** [comment]
Feel free to sketch out some options, and I'll be happy to review, so that you don't spend time on an implementation that might not get merged. I apologize that I haven't the time at the moment to research some options myself!

**Comment by stefanosc** [comment]
Okkie dokkie 😊
I'll invest some time during the next week and we'll see how it goes!

Have a great day.

**Comment by stefanosc** [comment]
@jpmckinney good day to you.  
So I gave some thought to this feature and I have to say it is definitely rather complex, and I will have to consider if tackling it or not.

I took a look at mandrill and they not only have variables but they also offer constructs such as `if else` and `loops`  
a parser of this kind will involve more serious processing.  

My main question to you for now is: do you think it is still useful to only handle variables?  
This too may require more time than I can dedicate for now but I would be happy to consider it further and see if I can contribute to this project.

Let me know what you see.  
Thank you!

**Comment by stefanosc** [comment]
@jpmckinney I am going to close this for now, as I have explored other options.  
I will open a PR shortly
