### ISSUE TITLE
Upgrade Faraday dependency

### ISSUE THREAD

**Issue by maran** [jpmckinney/multi_mail#29]
Hi!

Faraday is set to 0.9.0, however Stripe 4.0 release however needs 0.13 or higher. Is there any chance multi_mail could relax the Faraday version a bit or does it specifically need to be 0.9.0?

**Comment by jpmckinney** [comment]
I made a release with a relaxed version. However, this gem is no longer maintained; so if it doesn't work with Faraday 0.13, you (or another user) will have to make a pull request with any necessary changes.
